module.exports={
    updateColumnName : `UPDATE LIST SET NAME = ? WHERE LIST_ID = ? ;`,
    updateCard : `UPDATE CARD SET CONTENT = ?, EXTRA_FILE = ? WHERE CARD_ID = ? ;`,
    insertCard : `INSERT INTO CARD(LIST_ID, CONTENT, EXTRA_FILE, WRITER_ID, ORDER_INDEX) VALUES(?, ?, ?, ?, ?);`,
    getOrderIndex : `SELECT COUNT(*) AS CARD_COUNT FROM CARD WHERE LIST_ID = ? ;`,
    removeCard : `DELETE FROM CARD WHERE CARD_ID = ?`,
    getCardById : `SELECT * FROM CARD WHERE CARD_ID = ?`,
    getLastCard : `SELECT * FROM CARD WHERE CARD_ID = (SELECT MAX(CARD_ID) FROM CARD);`,
    getList : `
    SELECT
        LIST.NAME AS LIST_NAME,
        CARD.CONTENT AS CONTENT,
        CARD.EXTRA_FILE AS EXTRA_FILE,
        CARD.WRITER_ID AS WRITER_ID,
        CARD.CARD_ID AS CARD_ID,
        LIST.LIST_ID AS LIST_ID,
        CARD.ORDER_INDEX AS ORDER_INDEX
    FROM
        (SELECT BOARD_ID FROM BOARD WHERE USER_ID = ?) AS BOARD
    JOIN
        LIST
    ON
        BOARD.BOARD_ID = LIST.BOARD_ID
    JOIN
        CARD
    ON
        LIST.LIST_ID = CARD.LIST_ID;`
}